In [1]:
# COO format matrix A
v = [5, 8, 3, 6]
COL_INDEX = [0, 1, 2, 1]
ROW_INDEX = [0, 1, 2, 3]

# vector
x = [10, 20, 30, 40]

# y = Ax
# A = [[ 5  0  0  0]
#     [  0  8  0  0]
#     [  0  0  3  0]
#     [  0  6  0  0]]
# x = [10,
#      20,
#      30,
#      40]
y = [0, 0, 0, 0]
m = len(v)  # the number of non-zero values
for i in range(m):
    value = v[i]
    col = COL_INDEX[i]
    row = ROW_INDEX[i]
    y[row] += value * x[col]
print(y)


[50, 160, 90, 120]


In [2]:
# CSR format matrix A
v = [10, 20, 30, 40, 50, 60, 70, 80]
COL_INDEX = [0, 1, 1, 3, 2, 3, 4, 5]
ROW_INDEX = [0, 2, 4, 7, 8]

# vector
x = [1, 2, 3, 4, 5, 6]

# y = Ax
y = [0, 0, 0, 0]
m = ROW_INDEX[-1]  # the number of non-zero values


"""
In each row, figure out two things:
- 1. what are the non-zero elements?
= 2. their corresponding col idx.
"""

for i in range(len(ROW_INDEX) - 1):
    row_index_start = ROW_INDEX[i]
    row_index_end = ROW_INDEX[i + 1]

    for j in range(row_index_start, row_index_end):
        # Length of the range list is the number of valid value in each row.
        # v[j]：non-zero element
        # COL_INDEX[j]：corresponding col idx

        col = COL_INDEX[j]
        y[i] += v[j] * x[col]

print(y)

[50, 220, 740, 480]


In [2]:
import numpy as np


def dot_product(a, b):
    sum = 0
    for j in range(len(a)):
        sum += a[j] * b[j]
    return sum


A = np.array([[1, 0, 3], [0, -1, 4], [-2, 5, 0]])
print(A)

x = np.array([1, 2, 0])
print(x)

# method 1: calculate by definition
y = np.zeros(3)
print(y)

for i in range(3):
    y[i] = dot_product(A[i, :], x)
print(y)

# method 2: use matmul in numpy
z = np.matmul(A, x)
print(z)

[[ 1  0  3]
 [ 0 -1  4]
 [-2  5  0]]
[1 2 0]
[0. 0. 0.]
[ 1. -2.  8.]
[ 1 -2  8]
