In [ ]:
import numpy as np
import pickle

# load our CSR matrix
f = open("v.pickle", "rb")
v = pickle.load(f)
f = open("COL_INDEX.pickle", "rb")
COL_INDEX = pickle.load(f)
f = open("ROW_INDEX.pickle", "rb")
ROW_INDEX = pickle.load(f)

print(v)
print(COL_INDEX)
print(ROW_INDEX)

num_nodes = len(ROW_INDEX) - 1
pi = np.ones(num_nodes) / num_nodes
print(pi)

alpha = 0.01
second_term = alpha * np.ones(num_nodes) / num_nodes
while True:
    new_pi = np.zeros(num_nodes)
    # (1-alpha)P * pi + alpha 1/n
    for i in range(len(ROW_INDEX) - 1):
        row_index_start = ROW_INDEX[i]
        row_index_end = ROW_INDEX[i + 1]

        for j in range(row_index_start, row_index_end):
            col = COL_INDEX[j]
            value = v[j]
            new_pi[i] += value * pi[col]
    new_pi = new_pi * (1 - alpha) + second_term * pi

    # check convergence by L1-distance(a, b) = sum_i |a_i - b_i|
    if np.sum(np.abs(new_pi - pi)) < 1e-4:
        break
    else:
        pi = new_pi

print(pi)

f = open("pi.pickle", "wb")
pickle.dump(pi, f)


[0.5        0.5        0.03225806 ... 0.14285714 0.14285714 0.14285714]
[  6547  15408  17793 ... 216687 256538 260898]
[      0       2      33 ... 2312483 2312490 2312497]
[3.54731947e-06 3.54731947e-06 3.54731947e-06 ... 3.54731947e-06
 3.54731947e-06 3.54731947e-06]
